### PR TITLE
SAPP-1797 composer2

### PR DESCRIPTION
**Pull request by singularo**
* Add hadolint config for Dockerfile checking
* Various tweaks the linting suggested
* Unlock composer so latest is installed
* hirak/prestissimo no longer needed, removed

### CODE REVIEW

**Comment by pingers** [comment]
:ship: 

Aren't we leaving the composer 2 changes in a separate tag though?

**Comment by pingers** [comment]
Yeah, this needs to merge to a branch like "composer2" - so we don't get composer 2 for Drupal 8.x builds.

**Comment by singularo** [comment]
We can do that. composer2 works fine with 8.9 though. Thats what I've done in ua-ccsp, its on 8.9 for now.

**Comment by singularo** [comment]
If we are going to tag/build this with composer2, I'll update the other MRs as well to be explicit about using the composer2 s2i image.

**Pull request merged**
